"""rename_table_good

Revision ID: 7bbb41ad63fd
Revises: 573f39141474
Create Date: 2024-04-15 09:43:50.033818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bbb41ad63fd'
down_revision: Union[str, None] = '573f39141474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('good',
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=True),
    sa.Column('good_name', sa.String(length=255), nullable=True),
    sa.Column('specifications', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('pic', sa.String(length=255), nullable=True),
    sa.Column('cost_price', sa.Integer(), nullable=True),
    sa.Column('sell_price', sa.Integer(), nullable=True),
    sa.Column('availably', sa.Boolean(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supply_id'], ['supply.supply_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('good_id')
    )
    op.drop_table('good1')
    op.drop_constraint('order_good_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'good', ['good_id'], ['good_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_good_id_fkey', 'order', 'good1', ['good_id'], ['good_id'], ondelete='CASCADE')
    op.create_table('good1',
    sa.Column('good_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supply_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('good_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('specifications', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pic', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cost_price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sell_price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('availably', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['supply_id'], ['supply.supply_id'], name='good_supply_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('good_id', name='good_pkey')
    )
    op.drop_table('good')
    # ### end Alembic commands ###
